### ISSUE TITLE
pending applications page needs new filter

### ISSUE THREAD

**Issue by roxanneweber** [BloomTech-Labs/underdog-devs-fe-a#256]
The pending applications page requires a new filter that allows the admin user to filter only applications that have been rejected. Currently there is no way to view these applications.

**Comment by sayerjk** [comment]
This might be something we can collaborate on (FE and Data Science), as we will need to start recording which applications get rejected because we don't have a system for keeping track of this in the DS database (MongoDB).
Potential DS tasks: 
- Create a new Collection to store rejected applicants. 
- Generate mock data of users with validate_status set to "denied", instead of only "approved" or "pending", as is now. 
-
