### ISSUE TITLE
Redux cleanup

### ISSUE THREAD

**Issue by mcfrr3** [BloomTech-Labs/underdog-devs-fe-a#316]
After reviewing several files for the Auth0 cleanup it became apparent that many of the redux files that exist currently are very unnecessary and add to confusion about the codebase. When I think about what needs to be saved to a global state, the biggest item I can think of is the user profile after they've been logged in. There appears to be a lot of duplication (similarly named slices of state that seem to have the same function) and cases where slices of state don't need to be global in the first place (the lifecycle slice that is being set in several places in the code but never used / consumed).

I propose a ticket to clean up the redux files that are not necessary (seemingly everything except for `currentUser` or `userProfile`, whichever is preferred)

**Comment by ashurik522** [comment]
Mike, I agree we very much need this ticket. The feature I am currently working on requires us to send the current users profile_id(DS generated)  and role. It would be optimal to have that information in global state. On the BE there is not currently a specific endpoint to extract this information so that we could set it in state.

**Comment by ryan-hamblin** [comment]
@ashurik522 happy to collab planning out the work in that ticket #330  

We have office hours tomorrow 10/28, let's jam.
